version 1.98-1.10

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2146,6 +2146,15 @@ then :
 fi
 
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
 if test -z "${CURL_CONFIG}" ; then
  # Extract the first word of "curl-config", so it can be a program name with args.
 set dummy curl-config; ac_word=$2
